"""Create a fresh bench-calc project, ready for `i2c run` at phase 1 PLAN.

    python examples/bench_calc/new_project.py <dest> [--backend pidev]
        [--model <id>] [--name <name>]

Copies the seed code and spec, scaffolds with `i2c init` (single backend,
Pattern B), records the one phase and moves to `phase=1 state=plan` through
`i2c state`, then makes the initial git commit the runner needs. The hidden
reference suite (reference/) is never copied in; grade with grade.py.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PHASE_RECORD = (
    '{"id": 1, "title": "calc-ops", "regime": "build", '
    '"dependencies": [], "status": "pending"}'
)
EXTRA_GITIGNORE = ("__pycache__/", ".pytest_cache/")


def _i2c(dest: Path, *args: str) -> None:
    subprocess.run([sys.executable, "-m", "i2c.cli", *args], cwd=dest, check=True)


def _git(dest: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-c", f"safe.directory={dest.as_posix()}", *args],
        cwd=dest, check=check, capture_output=True, text=True,
    )


def _toml(backend: str, model: str | None) -> str:
    lines = [
        "# bench-calc project (generated by examples/bench_calc/new_project.py).",
        "[run]",
        f'backend = "{backend}"',
    ]
    if model:
        lines.append(f'model = "{model}"')
    lines += [
        "",
        "[telemetry]",
        'test_cmd = "python -m pytest tests/acceptance/phase_{phase} -q"',
        "",
    ]
    return "\n".join(lines)


def create(dest: Path, *, backend: str, model: str | None, name: str) -> None:
    if dest.exists() and any(dest.iterdir()):
        raise SystemExit(f"refusing to overwrite non-empty {dest}")
    dest.mkdir(parents=True, exist_ok=True)
    shutil.copytree(HERE / "seed", dest, dirs_exist_ok=True)
    shutil.copytree(HERE / "spec", dest, dirs_exist_ok=True)
    # `i2c init` skips files that already exist, so these survive scaffolding.
    (dest / "i2c.toml").write_text(_toml(backend, model), encoding="utf-8", newline="\n")
    _i2c(dest, "init", "--name", name, "--backend", backend,
         "--run-split", "off", "--pattern", "B")
    _i2c(dest, "state", "append-record", "phases.json", PHASE_RECORD)
    _i2c(dest, "state", "set", "project.json", "phase=1", "state=plan")

    gi = dest / ".gitignore"
    present = gi.read_text(encoding="utf-8").splitlines() if gi.exists() else []
    missing = [ln for ln in EXTRA_GITIGNORE if ln not in present]
    if missing:
        with gi.open("a", encoding="utf-8", newline="\n") as f:
            f.write("".join(ln + "\n" for ln in missing))

    _git(dest, "init", "-q")
    if not _git(dest, "config", "user.email", check=False).stdout.strip():
        _git(dest, "config", "user.email", "bench@local")
        _git(dest, "config", "user.name", "bench")
    _git(dest, "add", "-A")
    _git(dest, "commit", "-q", "-m", "bench-calc: initial state (phase 1 plan)")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("dest", type=Path)
    p.add_argument("--backend", default="pidev", choices=("claude", "codex", "pidev"))
    p.add_argument("--model", help="Default model for every action ([run].model).")
    p.add_argument("--name", help="Project name. Default: the destination folder name.")
    args = p.parse_args(argv)
    dest = args.dest.resolve()
    create(dest, backend=args.backend, model=args.model, name=args.name or dest.name)
    print(f"created {dest}")
    print("next: cd there and run `i2c run` until state is audit_boundary, "
          f"then `python {Path(__file__).with_name('grade.py')} {dest}`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
